### ISSUE TITLE
Database Architecture

### ISSUE THREAD

**Issue by eric-zhu-uw** [eric-zhu-uw/request#1]
# Tables
`will be written in MySql`

### Users
1. user
2. pass (hashed)
3. userId
4. name

### Ledger (double-entry accounting, always balance = 0)
1. userId
2. transactionId
3. amount
4. date
5. description

### Requests (Accounts Payable/Receive design)
1. fromUserId
2. toUserId
3. date
4. amount
5. description

# Queries
1. Get all transactions related to an userId
2. Get current balance related to an accountId
3. Get all pending requests related to an accountId

# Commands
1. Allow user to accept a request
2. Allow user to send a request (different info depending on payback | vs item)

**Comment by jsun98** [comment]
posgre > mysql

**Comment by Tilmanator** [comment]
Fractional cents?

**Comment by Tilmanator** [comment]
Consider transaction ID as primary key, have debit and credit # as well as users. Allows slick active table references rather than multiple ledger queries and primary key design problem
